### ISSUE TITLE
error : not working on windows 8.1

### ISSUE THREAD

**Issue by loudoweb** [infinity8/StructuredXmlEditor#2]
Hello,

I'm unable to make it work. I've got an error on the first launch. 

> An unhandled exception occurred! The app has attempted to recover and carry on, but you may experience some weirdness. Report error?.

I can't create a new project neither.

**Comment by Lyeeedar** [comment]
I just pushed out a new build that fixes a load of bugs, and also shows more information in the exception message. Would you mind trying that and see if it fixes your issue? And if it doesnt could you tell me what the exception message says.

**Comment by loudoweb** [comment]
> An unhandled exception occurred!
> 
> Méthode introuvable : '!!0[] System.Array.Empty()'.
> 
> The app has attempted to recover and carry on, but you may experience some weirdness. Report error?

**Comment by Lyeeedar** [comment]
That means you need to install .Net 4.6. Why thats the error it reports I do not know. But the solution should be installing .Net 4.6

**Comment by loudoweb** [comment]
I confirm it's working now.
