### ISSUE TITLE
Spaces in paths for FileItem translate to %20 

### ISSUE THREAD

**Issue by JSandusky** [infinity8/StructuredXmlEditor#3]
The conversion of space characters into web URI results for FileItems in a bad path as far as the image preview and XML output are concerned.

Wrapping the final assignment in Uri.UnescapeDataString does the trick thus far, assuming that Browse() is the only place really touching those paths.

**Comment by Lyeeedar** [comment]
Thanks for reporting this, it is fixed in the 1.6.0 release.
