### ISSUE TITLE
Dynamic Node Name

### ISSUE THREAD

**Issue by bojjenclon** [infinity8/StructuredXmlEditor#9]
I see in changelogs that the ability to use ChildAsName was removed, is there currently any way to have a node's name be dynamic? For example, say I have a collection of weapon nodes that all have the same data contained within their root nodes, but said root nodes should be the name of the given weapon. Like so:

weapons
->axe
->->data
->sword
->->data

Is there a way to do this?

**Comment by Lyeeedar** [comment]
So you can do this by making weapons a collection, containing the structs axe, sword, etc. It will then have the weapon name as the element name.

The main thing that doesnt support dynamic node names is references, as their design means they can't do it at all (and instead use the meta:RefKey attribute to store the chosen node name).
